import { useState } from "react";

const AITask = () => {
  const [prompt, setPrompt] = useState("");
  const [tasks, setTasks] = useState([]);

 const generateTasks = async () => {  //starts async fn   

 if (prompt.length === 0) return; //if input empty then stop
  try {
    const res = await fetch("http://localhost:5000/generate-tasks", {   //Send request to my backend server at port 5000 and hit the /generate-tasks API route
      method: "POST",  
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ prompt }), //converting data into string for backend
    });

  
    if (!res.ok) {   //if backend fails handle error 
      const errorData = await res.json();  //get response and convert into JS object 
      console.error("Backend Error:", errorData);
      return;
    }

    const data = await res.json();
    console.log("AI RESPONSE:", data); 

    setTasks(data);  //save in state
  } catch (error) {
    console.error("Error:", error);
  }
};

  const saveTasks = () => {
    const user = JSON.parse(localStorage.getItem("user"));
  const key = `tasks_${user.email}`;

  const existing = JSON.parse(localStorage.getItem(key)) || [];

     const formattedTasks = tasks.map((t) => ({
    TaskName: t.title,
    Description: "Generated by AI",
    Status: t.Status,
    DueDate:"05-05-2026"
  }));
    const updated = [...existing, ...formattedTasks];
    localStorage.setItem(key, JSON.stringify(updated));
  };

  return (
    <div className="space-y-6">

      <div className="flex flex-col sm:flex-row gap-3">
        <input
          type="text"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="e.g Plan my day"
          className="flex-1 p-3 rounded-2xl border border-purple-100 focus:outline-none tracking-wider"
        />

        <button
          onClick={generateTasks}
          className="px-5 py-3 rounded-2xl bg-[#6D28D9] text-white font-bold hover:opacity-90"
        >
        Generate 
        </button>
      </div>


      {tasks.length > 0 && (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {tasks.map((task, index) => (
            <div
              key={index}
              className="p-5 rounded-3xl bg-white border border-purple-50 shadow-sm hover:shadow-md transition"
            >
              <h3 className="font-bold text-[#1E1B4B] mb-2">
                {task.title}
              </h3>

              <p className="text-xs font-bold text-[#6D28D9]">
                {task.Status}
              </p>
            </div>
          ))}
        </div>
      )}

      {/* Save Button */}
      {tasks.length > 0 && (
        <button
          onClick={saveTasks}
          className="px-6 py-3 rounded-2xl bg-green-500 text-white font-bold hover:opacity-90"
        >
          Save Tasks
        </button>
      )}
    </div>
  );
};

export default AITask;